### ISSUE TITLE
[PE-D] Documentation bug for unassign feature. 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T12-4/tp#209]
Issue with the difference in the title of the feature and its description

![image.png](https://raw.githubusercontent.com/Halpfrog/ped/main/files/3e65b342-11db-4d26-b436-0ceb6e057094.png).

feature is unassign but the explanation uses the word assign

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Halpfrog/ped#6

**Comment by brian16600** [comment]
Updated
