### ISSUE TITLE
[PE-D] Incorrect format, for finding tasks by date, listed in UserGuide 

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T12-4/tp#214]
When trying to find tasks by a datetime, i get thrown this error. I am following the command layout as specified in the UserGuide 

![image.png](https://raw.githubusercontent.com/waffledood/ped/main/files/7f99533e-84e2-4b0e-91f6-a8adc4d8ec13.png)

The error shown in the app says to use the d/ tag instead of the dt/ tag written in the UserGuide

-------------
Labels: `severity.High` `type.DocumentationBug`
original: waffledood/ped#5

**Comment by snss231** [comment]
update /d to /dt in app, update UG
