### ISSUE TITLE
[PE-D] Does not allow same contact name with different details

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T12-4/tp#222]
![Screen Shot 2022-04-01 at 2.54.49 PM.png](https://raw.githubusercontent.com/riakhaitan/ped/main/files/f00c9b7f-b6ea-476e-b644-dd24671c6b1c.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: riakhaitan/ped#2

**Comment by snss231** [comment]
ok

**Comment by brian16600** [comment]
Fixed
