### ISSUE TITLE
[PE-D] Documentation of findt command inconsistency

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T12-4/tp#223]
Examples under findt command in the user guide have "find" as the command.

![image.png](https://raw.githubusercontent.com/Decaxical/ped/main/files/87e27267-b78f-4cf3-b85b-cc406286d352.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Decaxical/ped#4

**Comment by brian16600** [comment]
Updated
