### ISSUE TITLE
[PE-D] Takes invalid year "0001"

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T12-4/tp#228]
![Screen Shot 2022-04-01 at 3.00.46 PM.png](https://raw.githubusercontent.com/riakhaitan/ped/main/files/283b0a15-81cd-4a65-a12f-d126c0002f36.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: riakhaitan/ped#5

**Comment by snss231** [comment]
dupe
