### ISSUE TITLE
[PE-D] Duplicate tasks 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T12-4/tp#235]
Are duplicate tasks allowed in the application? I am able to enter duplicate tasks (same name & same time) 

Perhaps the team can clarify in the User Guide 

![image.png](https://raw.githubusercontent.com/waffledood/ped/main/files/bfeeb7bf-7213-4580-97ac-3b0d0b1b2c40.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: waffledood/ped#9

**Comment by snss231** [comment]
![Uploading image.png…]()

**Comment by snss231** [comment]
clarify in ug

**Comment by brian16600** [comment]
Clarified in UG
