### ISSUE TITLE
Add task

### ISSUE THREAD

**Issue by snss231** [AY2122S2-CS2103T-T12-4/tp#46]
Create an entity for "Task", which contains:
- String description
- DateTime

Create and update relevant classes in Logic, Parser, Model, Storage, UI

**Comment by snss231** [comment]
As a user I can keep track of my tasks

**Comment by brian16600** [comment]
Update Task with new parameter: Tag to represent tagging of a task
Update AssignCommand, UnassignCommand, AddTaskCommand to reflect the tagging
Update test cases in SampleDataUtil
Update Structure of Task object to include Tag
Update ReadOnlyTaskList interface to add addTask()

Clean up documentation of UG and various methods

**Comment by brian16600** [comment]
To be added: Uniqueness check for Tag to ensure no repeat and display tag in UI
