### ISSUE TITLE
Error regarding Assign and Unassign feature

### ISSUE THREAD

**Issue by junrong98** [AY2122S2-CS2103T-T12-4/tp#73]
To reproduce error: Just enter the command `assign 1` or `unassign 1` which will result in `java.lang.reflect.InvocationTargetException`.

Possible fix: Check if prefix `p/`  exists in the respective parser before command creation.

However, from the `MESSAGE_USAGE` seems like the prefix is an optional field `[/p]`.

**Comment by snss231** [comment]
Thanks for letting me know 👍  working on a fix
