### ISSUE TITLE
Leave contact list unchanged upon view empty person list

### ISSUE THREAD

**Issue by snss231** [AY2122S2-CS2103T-T12-4/tp#99]
Currently, if user views task and the task has no contacts, the displayed contact list is changed to empty.

Let's leave the contact list unchanged if a view command is executed and there are no contacts related to the task viewed.

**Comment by snss231** [comment]
Also minor grammar issue: There were no contact assigned to this task." -> "There are no contacts assigned to this task."

**Comment by junrong98** [comment]
Let's say Task 1 has 2 person assigned. And task 2 has no one.

User do `View 1` followed by `View 2`. Would you prefer if,

1. The `Contact` output shows all the contacts
2. Continue showing `View 1` contacts?

**Comment by snss231** [comment]
i think no change is more natural, but either works IMO
